version: "3.1"
services:
  book_task:
    build: .
    image: book_task
    command: "python manage.py runserver 0.0.0.0:7000"
    ports:
      - "7000:7000"
    expose:
      - 7000
    depends_on:
      - db
    volumes:
      - ./:/opt/book_task

  db:
    image: mariadb:10.1
    volumes:
      - ./.docker/mariadb:/var/lib/mysql
    expose:
      - "3306"
    environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes


volumes:
  database: